### ISSUE TITLE
Pinned `foldl` dependency does not conform with `playground-common`'s one

### ISSUE THREAD

**Issue by swtwsk** [Liqwid-Labs/plutus-extra#11]
When attempting to use `plutus-extra` in a project, `cabal` throws an error:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: playground-common-0.1.0.0 (user goal)
[__1] trying: foldl-1.4.11 (dependency of playground-common)
[__2] next goal: plutus-extra (user goal)
[__2] rejecting: plutus-extra-1.0 (conflict: foldl==1.4.11, plutus-extra =>
foldl^>=1.4.12)
[__2] fail (backjumping, conflict set: foldl, plutus-extra)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: foldl, plutus-extra, playground-common
```

It seems that pinned `foldl` in `plutus-extra` is expecting higher `foldl` version than required by `playground-common`.

**Comment by kozross** [comment]
This is quite surprising. According to `cabal freeze`, our overall dependencies include `foldl-1.4.12`. What Plutus revision is that project using? Does it differ from `289ac956a33c14fe1d75d6c0a6d6100f96a7d22c`?

**Comment by swtwsk** [comment]
Yes, it was a problem with a project trying to depend on `plutus-extra`. It was using older **Plutus**, thus the incompatibility. Closing the issue then.
