### ISSUE TITLE
Export some Internals for building ScriptContext from ContextBuilder

### ISSUE THREAD

**Issue by t1lde** [Liqwid-Labs/plutus-extra#123]
I find it would be helpful to have some direct access to the ScriptContext, for debugging workflows or otherwise. But the guts ( compileSpending and others) are very well hidden in an Internal module. 
It would IMO be useful to export some of this.

**Comment by kozross** [comment]
What kind of API would you like to see @t1lde?

**Comment by t1lde** [comment]
Nothing fancy, just anything to make retrieving a constructed ScriptContext possible
