### ISSUE TITLE
Missing key semantics for `Value`

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutus-extra#124]
A missing currency key in a `Value` map is semantically identical to a value of 0:

> A cryptocurrency value. This is a map from 'CurrencySymbol's to a
quantity of that currency.
>
> Operations on currencies are usually implemented /pointwise/. That is,
we apply the operation to the quantities for each currency in turn. So
when we add two 'Value's the resulting 'Value' has, for each currency,
the sum of the quantities of /that particular/ currency in the argument
'Value'. The effect of this is that the currencies in the 'Value' are "independent",
and are operated on separately.
>
> Whenever we need to get the quantity of a currency in a 'Value' where there
> is no explicit quantity of that currency in the 'Value', then the quantity is
> taken to be zero
>
> See note [Currencies] for more details.

and the referenced note:

> The 'Value' type represents a collection of amounts of different currencies.
>
> We can think of 'Value' as a vector space whose dimensions are
currencies. At the moment there is only a single currency (Ada), so 'Value'
contains one-dimensional vectors. When currency-creating transactions are
implemented, this will change and the definition of 'Value' will change to a
'Map Currency Int', effectively a vector with infinitely many dimensions whose
non-zero values are recorded in the map.
>
> To create a value of 'Value', we need to specifiy a currency. This can be done
using 'Ledger.Ada.adaValueOf'. To get the ada dimension of 'Value' we use
'Ledger.Ada.fromValue'. Plutus contract authors will be able to define modules
similar to 'Ledger.Ada' for their own currencies.

**Comment by kozross** [comment]
This means that we have to ensure that we don't generate `Value`s with zero values in the 'inner map'. This should be a reasonably straightforward (and invisible) fix.
