### ISSUE TITLE
Make `toTestValidator` and `toTestMintingPolicy` more generic

### ISSUE THREAD

**Issue by t4ccer** [Liqwid-Labs/plutus-extra#140]
Currently `toTestValidator` and `toTestMintingPolicy` fix `ScriptContext` to one imported from `Plutus.V1.Ledger.Contexts` and it is impossible to use custom contexts (which are useful when optimizing script size) without rewriting these functions. My proposal is to replace fixed `ScriptContext` with `FromData ctx` constraint, exactly like it is done with datums and redeemers.

**Comment by t1lde** [comment]
This would also be relevant to use with other custom ScriptContexts (spooky)

**Comment by kozross** [comment]
For @re-xyr - this is a _widening_ of a constraint, so I believe the PVP ranks this as a minor bump. The change should be fairly straightforward: let me know if not.
