### ISSUE TITLE
Merging Plutus-Extra-the-library from LiqwidX-Contracts

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutus-extra#145]
This issue is in reference to the associated issue in https://github.com/mlabs-haskell/liqwidx-contracts/issues/38, filed here for visibility.

**Comment by re-xyr** [comment]
@peter-mlabs Hi, what's the status of this migration? From the linked issue, I see there isn't a clear list of definitions to migrate yet. If you need any actions from me, please let me know.

**Comment by peter-mlabs** [comment]
Hi, sorry about this -- I'm going to close the issue for now. We've decided to move over to plutarch, and the requisite version bumps mean that some things have broken in the legacy code that simply aren't worth the time to fix right now. There may be a handful of utility types/functions that would be worthwhile re-implementing in plutarch, and we'll push them upstream if so.
