### ISSUE TITLE
Add "scale" capability to numeric types

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutus-extra#150]
Following a conversation between @kozross and I yesterday, there is a use case for the ability to perform (essentially) scalar multiplication over a field, in the sense of:

`scale :: Natural -> NatRatio -> NatRatio`

or 

`scale :: Integer -> Ratio -> Ratio`

It would be nice to have this capability to avoid unnecessary type conversion.

**Comment by kozross** [comment]
For clarity, `scale` comes from the `Module` type class. Additionally, we now have this upstream for [`Rational`](https://github.com/input-output-hk/plutus/commit/6d8d25d1e84b2a4278da1036aab23da4161b8df8), so it makes sense for `NatRatio` to have it too.

There is also need for support in `plutus-laws`, as we may want other instances in the future, and we want to ensure they're law-abiding.

**Comment by sergesku** [comment]
Unfortunately, approach with `Module s v` will not work for either `NatRatio` or `Natural` due to `Module s v` constraints:
```haskell
class (Ring s, AdditiveGroup v) => Module s v | v -> s where
```

I think We can go ahead with `scaleNat`:
```haskell
scaleNat :: forall (a :: Type). AdditiveMonoid a => Natural -> a -> a
```
