### ISSUE TITLE
Export `utxoAtComputedAddress` and implement `utxoAtAddress`

### ISSUE THREAD

**Issue by samuelWilliams99** [Liqwid-Labs/plutus-extra#155]
[Plutus.Contract.Test.Extra](https://github.com/Liqwid-Labs/plutus-extra/blob/master/plutus-extra/src/Plutus/Contract/Test/Extra.hs#L428) implements the function `utxoAtComputedAddress` but does not export it.
On top of this, unfortunately, PlutusTx does not implement a 
```haskell
utxoAtAddress :: Address -> (UtxoMap -> Eff effs Bool) -> TracePredicate
```
(constraints omitted for brevity) which would be very useful to have.
(Predicate is impure following definition of `utxoAtComputedAddress`, it could instead be pure)

**Comment by kozross** [comment]
@re-xyr This should be a straightforward minor bump.

**Comment by re-xyr** [comment]
There are some problems with implementing such a `utxoAtAddress`:

- Since `TracePredicate` has a fixed `effs` we need the constraint `effs ~ '[Reader InitialDistribution, Error EmulatorFoldErr, Writer (Doc Void)]` which can be unwieldy in some cases;
- We'll still need the `contract w s e a` and `ContractInstanceTag` parameters.

ping @kozross if you have any ideas on how to improve this; at the same time I'll draft an implementation with those caveats.

**Comment by samuelWilliams99** [comment]
Can we not use a similar implementation to [valueAtAddress](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/src/Plutus.Contract.Test.html#valueAtAddress) but instead of using `Folds.valueAtAddress :: Address -> EmulatorEventFold Value`, use `Folds.utxoAtAddress :: Address -> EmulatorEventFold UtxoMap`?

**Comment by samuelWilliams99** [comment]
```haskell
-- | Check that the funds at an address meet some condition.
utxosAtAddress :: Address -> (UtxoMap -> Bool) -> TracePredicate
utxosAtAddress address check =
    flip postMapM (L.generalize $ Folds.utxoAtAddress address) $ \utxoMap -> do
        let result = check vl
        unless result $ do
            tell @(Doc Void) ("UTxOMap at address" <+> pretty address <+> "was" <+> pretty utxoMap)
        pure result
```

**Comment by samuelWilliams99** [comment]
The `Eff` I had in the predicate was optional, the bottom line states it is fine to be pure

**Comment by kozross** [comment]
@re-xyr I don't think there's a lot you can do about this without diving into `Eff` internals. I'd say that drafting an implementation with these caveats is a good start; we can see if it can be improved somewhat once we have something to work with.

**Comment by re-xyr** [comment]
> Can we not use a similar implementation to valueAtAddress

Good idea. I have switched to that implementation.
