### ISSUE TITLE
`arbitrary` `PubKeyHash` should be fixed-length

### ISSUE THREAD

**Issue by AriFordsham** [Liqwid-Labs/plutus-extra#165]
The `Arbitrary` instance for `PubKeyHash` directly inherits `BuiltinByteString`, which generates bytestrings of arbitrary length.

This is incorrect for `PubKeyHash`, as `PubKeyHash` is always 256 bits long.

**Comment by kozross** [comment]
Thanks for this, definitely needs fixing.

**Comment by AriFordsham** [comment]
Can we close this in light of #168?
