### ISSUE TITLE
Provide a simple way to build `ScriptContext`

### ISSUE THREAD

**Issue by Renegatto** [Liqwid-Labs/plutus-extra#171]
# Motivation
Sometimes we would like to painlessly make `ScriptContext` for tests that doesn't deal with `tasty` framework or `tasty-plutus` testing method.

# Design
Preferably, would be nice to get it out of `ContextBuilder` since its building handy enough.

Thinking little bit forward, most of the time users would need to make some changes to a stuff they got from `ContextBuilder`. Making changes to `ScriptContext` directly is not so easy at least because it's too untyped/reduced.

So, would be nice to have a way to convert `ContextBuilder` into some more typesafe and conveinient representation than `ScriptContext`. The one that user could keep painlessly modify before finally reduce it to `ScriptContext`.
Let's call it `PreContext` for now.
So, simplified, the proposal is to make those:
```hs
data PreContext = ...
buildPreContext :: ContextBuilder -> PreContext
makeScriptContext :: PreContext -> ScriptContext
``` 
# Open questions

- The design of `PreContext` (and a what is the more suitable name for it)
- Is this possible to make it useful not only for tests?

**Comment by kozross** [comment]
I think the easiest way would be to break out the `ContextBuilder` machinery into its own sublibrary (`plutus-context-builder`). This also relates to #123.

**Comment by adamczykm** [comment]
I have been working with `tasty-plutus` in LiqwidX project, where, I think, I've met similar requirements/need. I hope that I'm not mistaken in finding it related. 

The way I have approach it is as follows:
- to provide more type-safety and convenient context editing I decided to implement one for one of the projects endpoint schemas

```purescript
data TxContext = TxContext
  { _vaultManagerContextName :: String
  , _vaultManagerScriptCtx :: ScriptTxContext VaultManagerScript
  , _repayScriptCtx :: ScriptTxContext RepayScript
  , _vaultScriptCtx :: ScriptTxContext VaultScript
  , _userWalletCtx :: PubKeyTxContext
  , _mintingValue :: Maybe Value
  , _outputLqxHolders :: Maybe Value
  , _extraSignatories :: [PubKeyHash]
  }
  deriving stock (Prelude.Show, Generic)

makeLenses ''TxContext
```

- then you need a type-safe way to get to the `ContextBuilder

```purescript
prepareContextBuilder ::
  forall (s :: Type).
  ValidatorInputSelector s ->
  TxContext ->
  ( TestData (ForSpending s)
  , TP.ContextBuilder (ForSpending s)
  )
```
It eventually opened the possibility of convenient property testing with `tasty-plutus` library that includes tx context disturbing.

```purescript
validatorProperty ::
  forall (s :: Type).
  (Typeable (RedeemerType s), Typeable (DatumType s)) =>
  ValidatorInputSelector s ->
  String ->
  Methodology TxContext ->
  (TxContext -> Outcome) ->
  WithScript (ForSpending s) ()
```

```purescript
  testProperty
    "User PKH, and validators hashes are preserved in vault."
    ( datumPartPreserved vaultScriptCtx borrowerIdL
        <> datumPartPreserved vaultScriptCtx repayValidatorHashL
        <> datumPartPreserved vaultScriptCtx vaultManagerValidatorHashL
    )


  testProperty
    "The exchange rate oracle must not be outside of the trusted sources."
    ( ValidatorProperty
        (disturbContextPart exchangeRateOracleMsg)
        ( \ctx -> case ctx ^? exchangeRateOracleMsg of
            Nothing -> False
            Just (OracleMessage pk _) -> pk == Cfg.oracleUser.pubKey
        )
    )
```

I hope it can shed some light/help with the ideation in the decision process for this issue

**Comment by kozross** [comment]
@adamczykm Does the solution proposed in #176 fit your needs? If not, please let us know.
