### ISSUE TITLE
Add support for serializing and de-serializing `Address`

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#172]
The code in the following module has been repeated at least twice already:

https://github.com/mlabs-haskell/CardStarter-bulk-airdrop-script/blob/sam/various-fixes/src/FakePAB/Address.hs

IOHK keeps expanding the use of the `Address` data type, and it appears to be the future. However they provide no obvious way to serialize and de-serialize it to/from textual representation. That representation is described in https://cips.cardano.org/cips/cip19/ and the reference implementation linked from there *seems* to handle the conversion between the textual and binary forms of the address. The binary form *may* be exactly what the `instance Serialise Address` provides, but I'm not sure. If so, the conversion `Address -> Text` could be a simple composition of two functions but it's so difficult to discover and confirm this that it would still be good to have it in `plutus-extra`.

**Comment by kozross** [comment]
@blamario So basically, you'd want `addressToText :: Address -> Text`, and also `addressFromText :: Text -> Maybe Address` or so?

**Comment by blamario** [comment]
Yes, though `addressFromText :: Text -> Either Text Address` would be better. The address text may be coming directly from the end user, so we want to be able to report the exact problem.

**Comment by kozross** [comment]
@re-xyr Put this in `plutus-extra`-the-library, in a place you consider appropriate. The signatures we want are:

* `addressToText :: Address -> Text`; and
* `addressFromText :: Text -> Either Text Address`.

Minor bump should do.

**Comment by blamario** [comment]
Did I say twice?
https://github.com/Plutonomicon/cardano-browser-tx/pull/66
Mind you this is Purescript, but still.

**Comment by samuelWilliams99** [comment]
The addressToText will likely also need a `NetworkId`

**Comment by kozross** [comment]
@samuelWilliams99 Why would this be necessary?

**Comment by kozross** [comment]
@re-xyr Also, please combine this with #175.

**Comment by samuelWilliams99** [comment]
> @samuelWilliams99 Why would this be necessary?

Serialisation of an address depends on the network. Specifically the prefix "addr1*q" vs "addr_test1*u", and the last 6 characters.
If we want the serialisation to be usable on testnets, we'll need to specify.

**Comment by kozross** [comment]
@samuelWilliams99 So wouldn't it also be needed for deserialization, or am I missing something here?

**Comment by samuelWilliams99** [comment]
yes, i believe only serialisation
