### ISSUE TITLE
The current `instance Arbitrary Address` causes run-time errors in Cardano

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#174]
Specifically "Staking pointers are not supported", triggered by

https://github.com/input-output-hk/plutus-apps/blob/46e831e49287c3a04f83497b9dd9e70718092cde/plutus-ledger/src/Ledger/Tx/CardanoAPI.hs#L490

This was ultimately caused by the `Arbitrary` instance for `Address` that generates all possible staking credentials, including the currently unsupported ones.

```
instance Arbitrary Address where
  arbitrary = Address <$> arbitrary <*> arbitrary
  shrink (Address cred sCred) = Address <$> shrink cred <*> shrink sCred
```

It's unfortunate, but as long as `plutus-extra` is locked to an incomplete implementation of `plutus-apps` it will have to work around its issues.

**Comment by kozross** [comment]
@blamario What do you think the best solution to this would be? I definitely think this is a bug, but I'm not sure what we can do to fix it.

**Comment by samuelWilliams99** [comment]
Could we not just build the address enforcing the use of the `StakingHash` constructor in the StakingCredential of the address?
Alternatively, perhaps a newtype wrapper specifically named for omitting StakingPtrs, then we coerce it when using

**Comment by blamario** [comment]
The simplest short-term solution would be to always generate `Nothing` in the staking credential. This might be an overkill even for the current Plutus, I haven't carefully examined the code path that leads to the error. And of course we'd need to remember to generalize the instance once Plutus is ready for it.

I don't have any better solution either. The `newtype` @samuelWilliams99 suggests would push the problem to the client code, and if you're going to do that it's probably better to just put a warning in the code. Maybe a `WARNING` pragma. It's usually possible to adjust the `Arbitrary` instance once you know you need to do it.

**Comment by samuelWilliams99** [comment]
I don't like forcing the staking to always be Nothing, as that's an important part of an Address. Especially in the usecase for which you found this bug, we definitely would need staking addresses to come through.

**Comment by samuelWilliams99** [comment]
I also don't think that modifying the Address Arbitrary to remove a case is good either, it should remain total.
I think our best bet here is a named alternative that explicitly doesn't have the pointers, with a warning. Then, once plutus supports these pointers properly, we deprecate it. What do you think?

**Comment by samuelWilliams99** [comment]
Following further on the issue itself, what exactly isn't supporting these pointers? Could any contract support addresses with staking pointers in plutusTx at this time?

**Comment by blamario** [comment]
I didn't get any stack trace, but my workaround was
```
-    [ testProperty "Invertible toABI" (invertibleTest @DepositLPEventParams)
+    [ testProperty
+        "Invertible toABI"
+        -- TODO : Revert the workaround once it's upstreamed, https://github.com/Liqwid-Labs/plutus-extra/issues/174
+        (\x@DepositLPEventParams {dlpCardanoAddress} -> isNothing (stakingCredential dlpCardanoAddress) ==> invertibleTest x)
```
where
```
invertibleTest a = (toABI >=> fromABI $ a) === pure a
```

so it's about the serialization of `Address` to `Text`. If we fix issue #172 first perhaps we can switch to our own solution and work around the Plutus bug.

**Comment by samuelWilliams99** [comment]
So is it our serialisation that uses a plutus function that doesn't support StakingPtrs?

**Comment by blamario** [comment]
So you're saying we should generate addresses with `Nothing` and with `Just StakingHash` but not with `Just StakingPtr`, correct?

**Comment by samuelWilliams99** [comment]
Exactly that, yes, since StakingPtrs seem pretty undersupported in plutus generally at the moment. We should however still attach a warning, stating that the instance will change once StakingPtrs become better supported

**Comment by kozross** [comment]
OK, let's close out #172, then repair this.
