### ISSUE TITLE
Add mustPayToAddress

### ISSUE THREAD

**Issue by nazrhom** [Liqwid-Labs/plutus-extra#184]
With the recent Plutus changes to the Address representation, we found ourself in need of a helper function such as:

```
mustPayToAddress :: Address -> Value -> TxConstraints i o
```

which takes care of unpacking the Address and returning the correct TxConstraints. This is what we are currently using:

```
mustPayToAddress :: Address -> Value -> TxConstraints i o
mustPayToAddress (Address (PubKeyCredential pkh) (Just (StakingHash (PubKeyCredential skh)))) =  mustPayToPubKeyAddress (PaymentPubKeyHash pkh) (StakePubKeyHash skh)
-- does not handle the case where the StakingCredential is a StakingPtr
mustPayToAddress (Address (PubKeyCredential pkh) _) = mustPayToPubKey (PaymentPubKeyHash pkh) 
mustPayToAddress (Address (ScriptCredential vh) _) = mustPayToOtherScript vh unitDatum
```

I was just wondering if it would make sense to add something like this in `plutus-extra` (possibly also handling the StakingPtr case correctly)?

**Comment by kozross** [comment]
In light of @blamario's comment, I'm closing this. @nazrhom - please let me know if what we have isn't suitable for you somehow.
