### ISSUE TITLE
MintingContexts can be constructed without minting anything

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#19]
Currently, there is no check to ensure that a `ContextBuilder` designed for minting actually mints anything. While this would certainly not lead to false positives when testing, it goes against the 'correct by construction' philosophy that `tasty-plutus` as a whole employs.

**Comment by re-xyr** [comment]
I'm thinking about this: have a "base" `ContextBuilder` type and an incremental `ContextBuilderChange` which is a `Monoid`, and can be applied to a `ContextBuilder` via a separate function. But this feels too much hassle that I'd personally prefer just leave things as is.

**Comment by kozross** [comment]
This is _kinda_ similar to what I was thinking for the rewrite. However, I definitely need to give this more thought.
