### ISSUE TITLE
The `Semigroup (ContextBuilder p)` instance has surprising behaviour

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#193]
Perhaps it's only me, but I really didn't expect

    sconcat $ signedWith "signature" <$> signatories

to end up with a single signature. The ultimate cause of this is the stupid `Semigroup` instance of `Map`, which simply drops the right value if the keys are the same. This instance is used a lot in the `Semigroup (ContextBuilder p)` instance:
```
  (ContextBuilder is os pkhs ds ms vis vos)
    <> (ContextBuilder is' os' pkhs' ds' ms' vis' vos') =
      ContextBuilder
        (is <> is')
        (os <> os')
        (pkhs <> pkhs')
        (ds <> ds')
        (ms <> ms')
        (vis <> vis')
        (vos <> vos')
```

I hope this wasn't intentional, but then again I don't understand the purpose of all the names I have to supply while building the context.

**Comment by kozross** [comment]
What kind of behaviour would you have expected? I'm happy to fix (and agree, the `Map` `Semigroup` instance is undesirable in many ways), but I'd like to know what you'd like to see here.

**Comment by blamario** [comment]
The constraints and other properties of `ContextBuilder` should not be silently dropped, is all I'm asking. Since I don't know why the design asks for all those names, I can't tell you what to do with them. If their only purpose is for logging or something, that could be accomplished by replacing `Map Text PubKeyHash` with `[(Text, PubKeyHash)]` in the definition of `ContextBuilder`. If you do need a `Map` there make it `Map Text (NonEmpty PubKeyHash)` and use `(Map.unionWith (<>) pkhs pkhs')` to combine them.

**Comment by sergesku** [comment]
The reason for introducing names was not logging, but the ability to edit  elements of the context. Therefore, each element is supposed to have a unique name. Perhaps I should have paid more attention to the description. I agree that this may not be the best solution. But if there are no specific requirements for the task, then you can always displease in something ...

**Comment by re-xyr** [comment]
The problem is that we want to have duplicate keys - but that way, we won't be able to edit elements by keys. 

I'm thinking if a multimap `Map Text (Set v)` will make sense here; i.e. `(<>)` can add elements to a key (`Map.unionWith Set.union a b`, but there is another operation (maybe call it `(</>)`) that replaces all elements in a key (`Map.union`).

**Comment by sergesku** [comment]
Why do you want to have duplicate keys? In this case, you can simply go back to `Sequence` instead of `Map`.

> sconcat $ signedWith "signature" <$> signatories

As far as I understand, in this example, @blamario just wants to ignore the keys altogether.
And this can be done with e.g.
```haskell
sconcat $ zipWith (\i s -> signedWith (tshow i) s) [1..] signatories
```

**Comment by blamario** [comment]
> As far as I understand, in this example, @blamario just wants to ignore the keys altogether.
> And this can be done with e.g.

That's exactly the workaround I've used. The question is, why do I need to jump through hoops in order to work around a feature I have no interest in? So far I've never needed to "edit individual elements by keys" in a `ContextBuilder`, and I don't understand why I should ever need it when I'm the one who's creating the `ContextBuilder` in the first place. This design is making simple things harder in order to make some complex tasks easier. That's seems like a bad tradeoff. Can anybody point to a practical example where this naming and editing is used?

**Comment by sergesku** [comment]
I think it's important to remember that you are not the only one using this library.  And what you don't need, others may need.
I don't have a real example, but in the tests I wrote (many similar scenarios with minor changes), this functionality would look good.
In any case, I tried to explain the idea of ​​this implementation.  What to do with it next is your decision.

**Comment by blamario** [comment]
If the goal of the design is to allow deleting and replacing parts of `ContextBuilder` by their name, why not add a function to do that explicitly, i.e.
```
deleteKey :: Text -> ContextBuilder -> ContextBuilder
```
The `Semigroup` instance should just do the most obvious thing and collect everything without dropping any pieces on the floor.

**Comment by kozross** [comment]
@blamario Is this necessary _just_ for signatures, or more generally?

**Comment by blamario** [comment]
I encountered it on signatures, but I suppose it's a general principle.

Also: *naming things* is well known as one of two difficult problems in computer science. While we're making the changes here, can we also make naming optional? I'd suggest replacing the current design:
```
input :: forall (p :: Purpose). Text -> SideUTXO -> ContextBuilder p
signedWith :: forall (p :: Purpose). Text -> PubKeyHash -> ContextBuilder p
...
```
with
```
name :: forall (p :: Purpose).  Text -> ContextBuilder p -> ContextBuilder p
deleteNamed :: forall (p :: Purpose).  Text -> ContextBuilder p -> ContextBuilder p
input :: forall (p :: Purpose). SideUTXO -> ContextBuilder p
signedWith :: forall (p :: Purpose). PubKeyHash -> ContextBuilder p
...
```

**Comment by kozross** [comment]
`name` as defined here would allow 'naming' arbitrary sub-contexts, which seems both tricky to do, and somewhat unnecessary. Would something like this be sufficient?

```
deleteNamed :: forall (p :: Purpose). Text -> ContextBuilder p -> ContextBuilder p
input :: forall (p :: Purpose) . Maybe Text -> SideUTXO -> ContextBuilder p
signedWith :: forall (p :: Purpose) . Maybe Text -> PubKeyHash -> ContextBuilder p
```

**Comment by kozross** [comment]
@blamario Yeah, that's fair enough. Let's go with that, then.

**Comment by blamario** [comment]
```
name n (ContextBuilder named) = ContextBuilder (Map.mapKeysMonotonic (n <>) named)
```
