### ISSUE TITLE
CPU/memory resource monitoring and benchmarking for `tasty-plutus`

### ISSUE THREAD

**Issue by maciej-bendkowski** [Liqwid-Labs/plutus-extra#194]
I think it'd be helpful to monitor the CPU/Mem consumption while running `tasty-plutus` tests. In it's most basic form, I'd like to be able to see  resource estimates while I run my tests (perhaps averaged across multiple executions if used for property testing). In a more advanced form, I'd like to be able to benchmark them. More specifically, I'd like run tasty tests with an additional `--benchmark` flag which would compare current resource estimates with some "golden" estimates stored on disk. I imagine the following workflow:

1. I execute `tasty` with a `--store-benchmark` flag which dumps resource estimates to disk.
2. Next, I work on my validator/minting scripts and execute `tasty` with a `--benchmark` flag. My tests are compared against the stored values and I get a summary. For instance, test (a) improved by 8% while test (b) decreased by 5%.

The only related resource I could find was https://playground.plutus.iohkdev.io/doc/plutus/howtos/analysing-scripts.html.

**Comment by kozross** [comment]
I see there being two issues here:

1. Slow-running tests, and wanting to know why; and
2. The ability to have on-chain benchmarks.

Those seem to want two distinct solutions. The first definitely sounds like something that should be controlled using a `tasty-plutus` flag; the second seems like it wants a dedicated library. Which is more urgent of the two?

**Comment by samuelWilliams99** [comment]
The former - we really just want to know the budget and such of any given quickcheck test - we don't even need ways to _confine_ it to some arbitrary value, just a way to know what it is

**Comment by maciej-bendkowski** [comment]
Indeed, I was thinking of addressing the former issue, and then perhaps moving to the latter one. Knowing the resource costs allow me to do my own, simple benchmarks _even without_ a more systematic solution to the latter issue.
