### ISSUE TITLE
Export the WrappedValidator constructor

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#198]
Sam was mightily annoyed at the mob coding session yesterday that this constructor wasn't exported from `Test.Tasty.Plutus.TestScript`. That leaves `toTestValidator` as the only way to construct a `WrappedValidator`, but this function expects a typed validator. It can't be used to wrap an untyped Plutus validator that errors out instead of returning `False`.

**Comment by kozross** [comment]
Can't we just add a function like `untypedToTestValidator` that does this exact thing? Exporting the constructor is something I'd rather not do.

**Comment by blamario** [comment]
Sure, if you prefer.

**Comment by re-xyr** [comment]
Keep in mind that in order for `tasty-plutus` to decide if a properly terminated script actually "validates", it looks for a line of log "tasty-plutus: Pass". Therefore not any untyped validator can work with `tasty-plutus` out of the box. I suggest we have an `untypedToTestValidator` like this:

```haskell
untypedToTestValidator ::
  (BuiltinData -> BuiltinData -> BuiltinData -> ()) -> WrappedValidator
untypedToTestValidator vl = WrappedValidator $ \d r p -> case vl d r p of
  () -> reportPass
```

**Comment by re-xyr** [comment]
@kozross Now that I think about it, why didn't we decide if a script succeeded based on whether it errors? That looks more straightforward than inspecting logs.

**Comment by re-xyr** [comment]
Additionally, simply exposing the `WrappedValidator` constructor won't enable you to construct a `TestScript` with an untyped validator - `TestScript`'s constructors expect to have the `CompileCode` of a typed validator for dumping purposes. Maybe we need to make it a `CompileCode` of an existensial type?

**Comment by kozross** [comment]
@re-xyr The reason for this is that some scripts (given certain preconditions) would still _run_, but not end up in a state that we wanted. I definitely remember some issue around this being a problem, though it was quite a while ago. If you think we can avoid it while breaking no tests, it'd certainly make the code much simpler.

**Comment by re-xyr** [comment]
>  would still run, but not end up in a state that we wanted

What does "state" refer to here? As I know a typed script can have 3 outcomes: returning `True`, returning `False`, or error. Are there any extra pieces of information (except logs) that we can also obtain for a script run?

> I definitely remember some issue around this being a problem, though it was quite a while ago

If you remember what are those issues, I can test that out.

> If you think we can avoid it while breaking no tests

Yes! - see #199.

**Comment by kozross** [comment]
@re-xyr I guess I can't remember exactly at this stage - should have documented it! I'd suggest opening a PR with the proposed improved interface: feel free to do an API break if you think you need it. We can then get people to try it out, and if there's no weirdness, we can adopt it; if we uncover any weirdness that didn't arise under the original formulation, then we'll know.
