### ISSUE TITLE
Mandated Nix version

### ISSUE THREAD

**Issue by pdavidow** [Liqwid-Labs/plutus-extra#209]
The README states:  _you will need Nix 2.4_
So, is that **exactly** that version, or **at least** that version?
Hopefully it's the latter, being that nix is already at 2.7

**Comment by kozross** [comment]
This is badly-phrased. You're right about it being a minimum version bound: we need at least 2.4 for flakes.

**Comment by kozross** [comment]
Fixed in [this commit](https://github.com/Liqwid-Labs/plutus-extra/commit/e3a227273b3dfdfdfb33261e91f7322c5acfde2f).
