### ISSUE TITLE
scaleNat is slow

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#213]
The current implementation of `scaleNat` is linear in its second argument (that is, the scale), which is extremely suboptimal. There are two fixes that need to be made for it:

1. Rewrite the current implementation to use [exponentiation-by-squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring) instead.
2. Use [`SPECIALIZE`](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/exts/rewrite_rules.html?highlight=fno%20specialize#specialisation) to boil down to multiplication for all cases where this is doable.

**Comment by kozross** [comment]
It's also important to 'pin this in place' with benchmarks.

**Comment by blamario** [comment]
Both `scaleNat` and the original `scale @Integer @Value` are pretty useless IMO. I'd much rather have `mapQuantities :: (Integer -> Integer) -> Value -> Value`. And there'd be no mistaking its complexity class.

**Comment by kozross** [comment]
@blamario `scaleNat` stems from the fact that `Module` is too strong in its requirements (should really have been `Semimodule` IMHO). Additionally, `scale` can be used to great effect on `Rational`s (and in fact, this bug was found on _exactly_ this kind of usage).

**Comment by re-xyr** [comment]
For 2) - do we need to consider off-chain types like `Int`?

**Comment by kozross** [comment]
@re-xyr Yeah, this is why the number of `SPECIALIZE`s required is practical: not a lot of instances.

**Comment by re-xyr** [comment]
Does the Plutus compiler actually pick up the rewriting rules? I did a small test and the script size didn't change after I added a rewriting rule.

**Comment by kozross** [comment]
@re-xyr I'm actually not sure about that. If it doesn't seem like it makes any difference, you can leave it to me to investigate.
