### ISSUE TITLE
SpendingTest can contain unrelated datums and redeemers

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#24]
When constructing a `SpendingTest`, nothing requires the datum and redeemer to be connected in any way. This is counter to our 'correct-by-construction' philosophy. Instead, these should be `DatumType` and `RedeemerType` of a particular type parameter.

**Comment by kozross** [comment]
@sergesku and @adamczykm - I'll let you decide how to proceed here.

**Comment by adamczykm** [comment]
@sergesku @kozross 
The only thing popping out is binding them with `ValidarTypes`. WDYT?

**Comment by kozross** [comment]
@adamczykm I'm in favour of this solution if you can make it work. My chief concern is bad type inference (type families are annoying like that). If you wanna give it a go, happy to assign you.

**Comment by sergesku** [comment]
I think the task is somewhat broader. We also have a "MintingPolicy" that should match the "Redeemer" used.
Thus instead `ValidatorTypes` we can use:
```
data Purpose where
  ForSpending :: forall datum redeemer. datum -> redeemer -> Purpose
  ForMinting :: forall redeemer. Redeemer -> Purpose
```

And I think the type parameter `(p :: Purpose)` is useless in `ContextBuilder` and we can stop using it.

**Comment by sergesku** [comment]
Atm the type parameter `(p :: Purpose)` is useless in `ContextBuilder`. We can consider to stop using it.
Currently we always create only polymorphic ContextBuilders. But it can come in handy in such situations (#33):
```
spendFromSelf :: Value -> datum -> ContextBuilder `ForSpending
```

**Comment by kozross** [comment]
The idea behind `Purpose` was to help in exactly the `spendsFromSelf` kind of situation. I agree it's not _very_ useful right now, so if we want to replace it, I'm happy to do that.

**Comment by adamczykm** [comment]
So we'd have, for example:
```haskell

addDatum ::
  forall (datum :: Type, redeemer :: Type).
  ToData datum =>
  datum ->
  ContextBuilder ('ForSpending datum redeemer)

```
?

**Comment by sergesku** [comment]
No, addDatum and all existing helpers don`t affect the `ContextBuilder`:
```haskell
addDatum ::
  forall (datum :: Type) (p :: Purpose).
  ToData datum =>
  datum ->
  ContextBuilder p
```
Therefore, I doubt that we need this parameter in ContextBuilder now.
