### ISSUE TITLE
Improve self-spending context construction

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#33]
As described in #31, the current interface is counter-intuitive. @nrutledge - given that you found this issue, what do you feel would be more usable and intuitive?

**Comment by adamczykm** [comment]
@sergesku shouldn't your changes close this issue?

**Comment by sergesku** [comment]
Hm. I don't think so. We have no a function like `spendFromSelf`. So we should probably add a description of what we can spend from the validator with `spendFromOther` using PubKeyHash configured with `localOptions`

**Comment by kozross** [comment]
@sergesku Would you be able to add such a description? This doesn't even need a version bump, since it's a documentation change.
