### ISSUE TITLE
Fix Hoogle in Nix

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#43]
Currently, our `nix-shell`-based Hoogle isn't correctly set up. There is a fix [here](https://github.com/mlabs-haskell/plutus-use-cases/pull/153) to repair this, as well as a general cleanup [here](https://github.com/mlabs-haskell/plutus-use-cases/pull/150).

**Comment by sergesku** [comment]
At the moment `make hoogle` works correctly in the `nix-shell`. Plutus packages are also included.
I suggest closing this ticket. If a specific problem is found, then it will be possible to deal with it in more detail.

**Comment by kozross** [comment]
@sergesku Agreed.
