### ISSUE TITLE
Arbitrary context for property tests, experience report

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#49]
I've managed to write my first property test, and apparently to catch a bug with it as well. That being said, I was stumped for a little while with the inability to vary the transaction context. The transactions in this project heavily rely on the context, especially the signature set.

In the end I worked around the issue by varying the datum and the redeemer more than I had intended. The property in the end needs to satisfy a *relation* between the datum, redeemer, and the context: if one of the three (i.e., context) is fixed, the desired relation can be set up by varying the other two.

I'm not sure how general this workaround is, and I'd probably have finished sooner were I able to follow my original plan, but this wasn't a big deal after all.

**Comment by sergesku** [comment]
Since version `5.0`, property-based testing allows you to create arbitrary but interconnected by your desired logic Datum, Redeemer and ContextBuilder. Take a look.

**Comment by blamario** [comment]
I agree, this issue is no longer relevant.
