### ISSUE TITLE
Monoid instance for `ContextBuilder`

### ISSUE THREAD

**Issue by sergesku** [Liqwid-Labs/plutus-extra#53]
From time to time I definitely feel a lack of a Monoid instance for `ContextBuilder`.

**Comment by Anteproperispomenon** [comment]
There's also the issue when you want to selectively toggle certain contexts, e.g. something like
`(if a then context1 else mempty) <> (if b then context2 else mempty)`

**Comment by kozross** [comment]
@re-xyr - could you handle this? It's a small change (minor version bump for `tasty-plutus`).

**Comment by re-xyr** [comment]
I'm afraid `mempty` defeats the purpose of #19. `Semigroup` perhaps makes more sense?

**Comment by kozross** [comment]
@re-xyr This is correct, but #19 requires an API break. We already have a `Semigroup` instance, and while this _does_ mean we can construct nonsensical values, we can _already_ construct nonsensical values as #19 indicates. This will (temporarily) make things more convenient, while in future, we can fix the API to not have either issue.
