### ISSUE TITLE
Unify `Example` and `Outcome`

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#61]
This will need to be done on `staging` as it's an API break.

**Comment by re-xyr** [comment]
`Outcome` is only used internally, so I don't think that is an API break. Or I missed something?

**Comment by kozross** [comment]
I guess we could just use `Example` for both, but I'm not 100% happy at the naming in this case.

**Comment by re-xyr** [comment]
I agree `Outcome` is actually a better name. Do you prefer any particular name?

**Comment by kozross** [comment]
I prefer `Outcome` as well. I guess I'd be OK with an API break for the sake of better naming.

**Comment by re-xyr** [comment]
Fixed by #78
