### ISSUE TITLE
Add `shouldValidateProducing` that returns a list of UTxOs

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#62]
This is a relatively simple extension that takes a small step toward the ability to test sequences of transactions. The idea is to add a function of signature

    shouldValidateProducing :: forall (p :: Purpose). Typeable p => String -> TestData p -> ContextBuilder p -> WithScript p [Input]

Feel free to substitute a better name. The point is that the returned `[Input]`value could be used in a following unit test:

    withValidator "my validator" (...) $ do
      myInputs <- shouldValidateProducing "initial transaction" myInitialData myInitialContext
      shouldValidate "second transaction" myOtherData (foldMap input myInputs)

The above assumes `ContextBuilder` is a `Monoid` as per issue #53, but that's orthogonal.

**Comment by re-xyr** [comment]
Does this function return the list of input UTxOs, or output UTxOs? To me it seems reasonable that it returns output UTxOs.

**Comment by blamario** [comment]
Yes, output UTxOs of the argument transaction.
