### ISSUE TITLE
Substitution testing for Plutus Eq

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#67]
Currently, we only check whether `Eq` is an equivalence relation. While this is good, one major source of bugs is something like so:

```haskell
data Foo = Foo {
    bar :: Bar,
    baz :: Baz
}

instance Eq Foo where
   x == y = (foo x == foo y) && (bar x == bar y)
```

Then, later, we add a new field to `Foo`, but forget to update the `Eq` instance:

```haskell
data Foo = Foo {
    bar :: Bar,
    baz :: Baz,
    quux :: Quux
}

instance Eq Foo where
   x == y = (foo x == foo y) && (bar x == bar y)
```

This will compile, and will still be an equivalence relation (in that all the tests will pass), but is wrong.

There are two possible ways to add substitution testing, but they're both quite onerous:

* Use the [approach taken by `quickcheck-classes`](https://hackage.haskell.org/package/quickcheck-classes-0.6.5.0/docs/Test-QuickCheck-Classes.html#v:substitutiveEqLaws). This is more principled, but requires defining `CoArbitrary` instances for all types to be so tested. This is not only deprecated (as we're meant to use `Function` now), meaning a redesign is needed, but also would mean a _large_ number of such instances would be required for Plutus types as well.
* Use an approach where we lean on `Generic` (or more likely `generics-sop`) to construct 'paired' instances which differ in one random field, then ensure that such instances compare inequal. This is more general (since it can also be used for `Ord`), but requires either `Generic` everywhere (which leads to custom type classes to ensure `Arbitrary` constraints are propagated through the structure properly) or use of `generics-sop` (which requires a lot of instances again). Lastly, this only really works for records, while the approach above works on anything.

Both of these require significant work, and it's not clear which is the better choice. Ideally, we want all of the following:

* Minimal need to define additional instances
* The most general approach possible (that is, extensible beyond `Eq`)
* Minimally-intrusive (that is, similar in spirit to all our other laws tests)
* Principled (covers as many cases as possible as thoroughly as possible)
* Produces good error messages with as narrow a context as possible

**Comment by kozross** [comment]
Upon further thought, the generalization requirement (that is, going beyond `Eq`) isn't really warranted if we have #68 defined. This reduces the requirements a bit, as now, our checklist is only:

* Minimal need to define additional instances
* Minimally-intrusive (that is, similar in spirit to our other laws tests)
* Principled (covers as many cases as possible as thoroughly as possible)
* Produces good error messages with as narrow a context as possible

This actually tips us _slightly_ in favour of the first approach, but it would be good to hear from others, especially those who have the context of existing codebases to consider.

**Comment by re-xyr** [comment]
I think it's possible that some `Eq` instances intentionally have some don't-care fields? I'm not sure whether doing this will make those instances illegal.

**Comment by kozross** [comment]
Those instances are definitely _very_ unusual, and almost always wrong. I don't think that making such instances illegal is a problem.

**Comment by samuelWilliams99** [comment]
> Those instances are definitely _very_ unusual, and almost always wrong. I don't think that making such instances illegal is a problem.

In this case it's probably fine to have an external function, not related to `Eq` to make it clear its not a full equality definition. However sometimes this isn't an option.
Regarding `CoArbitrary` vs `Fun`, both have generic implementations, we could probably, the instances probably wouldn't take long, assuming the generic instances are good.

Theres also a generic `Fun` instance from `CoArbitrary` `(Function a, CoArbitrary a, Arbitrary b) => Arbitrary (Fun a b)`, so I don't think using coarb is that bad.

**Comment by kozross** [comment]
Interesting to know that there's a `Generics` fallback for `Function` and `CoArbitrary` both! I think that seals the decision: `Function` is the right way to go here, especially due to its better shrinking behaviour.
