### ISSUE TITLE
Checks for agreement between Plutus Eq and Plutus Ord

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#68]
We want to ensure that they're not giving inconsistent answers. So, something like:

* If `x == y`, then `compare x y == EQ`; and
* If `x /= y`, then `compare x y /= EQ`.

**Comment by re-xyr** [comment]
What about operator agreement within the class, i.e. the laws:

```
x >= y = y <= x
x < y = x <= y && x /= y
x > y = y < x
x < y = compare x y == LT
x > y = compare x y == GT
min x y == if x <= y then x else y = True
max x y == if x >= y then x else y = True
```

**Comment by kozross** [comment]
Those are probably worth adding checks for - good catch!

**Comment by re-xyr** [comment]
> Those are probably worth adding checks for

Should I add them in #73 right away or make another PR?

**Comment by kozross** [comment]
Either or.
