### ISSUE TITLE
`GenForMinting` doesn't pass `Value` parameter

### ISSUE THREAD

**Issue by AriFordsham** [Liqwid-Labs/plutus-extra#76]
While `GenForSpending`'s function field accepts a `Value` parameter, `GenForMinting` does not.

It seems to me this is as useful, and is an oversight.

**Comment by kozross** [comment]
What would the `Value` parameter serve in this case? I guess it allows more precise generators and shrinkers?

**Comment by AriFordsham** [comment]
In my case, I need to test policies that depend on the value minted, so I can't use property tests without it.

**Comment by kozross** [comment]
Ah, OK. Understandable then.

**Comment by kozross** [comment]
Merged into `staging`.
