### ISSUE TITLE
Add `PlutusTx.Natural.length :: Foldable t => t a -> Natural`

### ISSUE THREAD

**Issue by blamario** [Liqwid-Labs/plutus-extra#81]
The definition is trivial, but this is the place for it.

**Comment by blamario** [comment]
`PlutusTx.Foldable.length` uses `foldl` for some reason, but I'd go with 

    {-# INLINEABLE naturalLength #-}
    naturalLength :: Foldable t => t a -> Natural
    naturalLength = getSum . foldMap (Sum . const [nat| 1 |])

**Comment by kozross** [comment]
@re-xyr You can add this to `plutus-extra`-the-library, PR against `master`. Minor version bump only.

**Comment by blamario** [comment]
FYI, I thought this alternative implementation might be better:

    naturalLength = (`appEndo` [nat| 0 |]) . foldMap (const $ Endo succ)

but it ended up taking 4 bytes more on-chain. I can't measure performance that easily.

**Comment by kozross** [comment]
This actually raises a very valid issue, which I think is larger than just this particular request. We probably want to have size checks on everything, and try and reduce those where possible. How did you measure the size of the implementations of `naturalLength` you suggested here?

**Comment by blamario** [comment]
I have existing tests using `fitsInto` and `fitsOnChain`, and they print out the exact size of the validator - which turns out to be very nifty for quick checks like this!

**Comment by kozross** [comment]
How did you get this specific function into a form that either of those would accept?

**Comment by blamario** [comment]
The function `naturalLength` is used by a validator, and those functions accept the validator. The test output is

    size
      validator fits on-chain:                                                                     OK
        Size: 4533B (~4.5KiB)
      validator fits into 5KiB:                                                                    OK
        Size: 4533B (~4.5KiB)

After I tried the alternative definition of `naturalLength`, the reported validator size went up to 4537B. The function is actually called in two places in the on-chain code, so depending on whether it was inlined or not I infer its size must have gone up by 2 or 4 bytes.

**Comment by kozross** [comment]
I wonder if there's a way we can check only that function as a component. This would allow a golden-testing-like approach for individual function checks to be made.

**Comment by t1lde** [comment]
Could we use TH to discover INLINEABLE functions? This might run into staging issues, though. Another problem is instantiating type variables. And whether there's any optimization pass in whole scripts that would make individual function sizing less meaningful...

**Comment by blamario** [comment]
Back on topic or nearly so, I now also had to implement `takeNatural :: Natural -> [a] -> [a]` in my code. So you might want to invoke the slippery slope argument, or to just take the slide and implement a counterpart to every function from `Data.List` that has `Int` in its signature.

**Comment by kozross** [comment]
@blamario There's some merit to this actually. Time for `plutus-foldable-traversable`?

**Comment by kozross** [comment]
I think it's a little bit outside the scope of `plutus-numeric`. I'm happy to consider other package names (maybe `plutus-list`?).

**Comment by kozross** [comment]
For @re-xyr: Start a new module `plutus-list` containing at least the following functionality:

* `length` (as above)
* `take` and `drop` (as above)
* `isSorted` and `isSortedOn` (using Plutus `Ord`)
* `isSortedMonotonic` and `isSortedMonotonicOn`, which ensures adjacent elements are `<` each other, rather than `<=`, again, based on Plutus `Ord`
* If you are confident, `ordNub` based on Plutus `Ord`

Feel free to add any additional functions you see fit. Use the other sublibraries as a basis for your work. Ensure you have property tests: `tasty-quickcheck` would work.

**Comment by kozross** [comment]
@blamario and @t1lde - I just had a thought regarding testing of individual function sizes. Currently, `tasty-plutus` uses [this method here](https://github.com/Liqwid-Labs/plutus-extra/blob/master/tasty-plutus/src/Test/Tasty/Plutus/Script/Size.hs#L179), which wants a `Script`. It's possible for us to use the Plutus compiler to produce `CompiledCode` corresponding to just the function, then pass said `CompiledCode` to `Plutus.V1.Ledger.Scripts.fromCompiledCode` to produce a `Script`, then measure. This is _kind of_ automatable.

Would this be a meaningful measure, or am I missing something here?

**Comment by re-xyr** [comment]
@kozross Not sure if this is worth a new package - maybe it'll suffice just adding them to `plutus-extra`?

**Comment by kozross** [comment]
@re-xyr `plutus-extra`-the-package is already a large scattershot collection. When you consider all the _testing_ that is required for `plutus-list`, it easily qualifies as a package in its own right, I think. Plus, having smaller, more focused packages will make it easier to maintain, and also involve fewer dependency updates for people who only need _some_ of the functionality.

**Comment by blamario** [comment]
If measuring from `CompiledCode` rather than `Script` would merely generalize the measurement, I don't see any downside. That being said, we're usually interested in the size of the whole script so I don't think this is worth much effort.

A terminological quibble: *monotonic* mathematically means consistently less-or-equal or greater-or-equal. Instead of `isSortedMonotonic` may I suggest `isSortedAndDistinct`? (I had suggested `isSortedAndNubbed` but it turns out nub is not a verb.)

**Comment by kozross** [comment]
I've heard the term 'monotonically increasing' used, so I feel it's defensible, if a bit unclear. How about `isAscending` instead?

**Comment by blamario** [comment]
Yes, `isAscending` is short and clear.

**Comment by kozross** [comment]
@re-xyr In addition to the other fixes, please rename `isSortedMonotonic` (and related functions) to `isAscending`.

**Comment by re-xyr** [comment]
The term I often see is "strictly monotonic". I looked up and also found "strict total order" (<) and "non-strict total order" (<=). So an alternative idea is "isOrdered" and "isStrictlyOrdered"; but that is still a long name.

**Comment by kozross** [comment]
That's also an option, but I think `isAscending` is clear enough, so let's go with that instead.
