### ISSUE TITLE
Fix `instance Arbitrary Value`

### ISSUE THREAD

**Issue by sergesku** [Liqwid-Labs/plutus-extra#82]
Atm we have an incorrect **Arbitrary** instance for **Value**, which is derived via **AssocMap**.

The problem is than Value uses different way for the **Eq** instance. 
Compared values combined in **These Integer Integer** and then **These Integer Integer** is analyzed.
So in the case of several identical keys a problem arises.

To fix this, we have to generate Value with unique keys, or normalize the value after generating, as we do in **liqwid-contracts**:
```
instance Arbitrary Value where
  arbitrary = foldMap (uncurry3 singleton) <$> arbitrary @[(CurrencySymbol, TokenName, Integer)]
  shrink = fmap (foldMap (uncurry3 singleton)) . shrink . flattenValue
    where
      uncurry3 :: (a -> b -> c -> d) -> (a, b, c) -> d
      uncurry3 f (a, b, c) = f a  b c
```

**Comment by Renegatto** [comment]
Should we have this instance at all, since it present in `Plutus.PAB.Arbitrary` and can lead to conflicting instance decalarations?

**Comment by kozross** [comment]
@Renegatto AFAIK, we're replacing Plutus's PAB with our own. Whether it has such an instance I don't know, but I will need to investigate. Thank you for bringing it to my attention.
