### ISSUE TITLE
Add helper to `tasty-plutus` to create partial contexts quickly.

### ISSUE THREAD

**Issue by Anteproperispomenon** [Liqwid-Labs/plutus-extra#87]
Often, when using `tasty-plutus`, I have a list of partial contexts that, when combined, should pass the validator, but should any individual partial context be missing, the combination of the rest should fail.

To help with this, in a project I was working on, I created a function that takes a list of pairs of the type `forall (p :: Purpose). [(ContextBuilder p, String)]` where the first element is the partial context and the second is the message when that context is missing, and converts it into a list of incomplete contexts as follows:
```
[ (context1, "Missing context 1")
. (context2, "Missing context 2")
, (context3, "Missing context 3")
]
```
would become
```
[ (context2 <> context3, "Missing context 1")
, (context1 <> context3, "Missing context 2")
, (context1 <> context2, "Missing context 3")
]
```
You can then run this in a `withValidator` block as follows:
```
mapM_ (\(ctx,str) -> shouldn'tValidate str input ctx) convertedContexts
```

**Comment by kozross** [comment]
That sounds like a useful thing to have. If you'd like to send a PR, please do so - this feels like a minor version bump, so against `master` is fine. Please also update the changelog and add a `@since`.

**Comment by Anteproperispomenon** [comment]
Which module should I put it in?

**Comment by kozross** [comment]
I'll let you make that call - there's a few possibilities, but since it's your contribution, you choose.

**Comment by Anteproperispomenon** [comment]
I can't upload my branch; I don't have write access.

**Comment by kozross** [comment]
You do now.
