### ISSUE TITLE
Change API for property-based script testing

### ISSUE THREAD

**Issue by Renegatto** [Liqwid-Labs/plutus-extra#89]
# Motivation
Currently `tasty-plutus` API for property-based testing have not enough expressiveness.
It can take some time to make special tools to cover most common script testing use cases, but even before that happen, API still must be useful, and allow users to express tools they need by themselves using it.
To achieve that makes sense to provide more general API than existing one, but having more expressive power (in cost of specialization). 
# Changes
Currently basis of property-based tests API is  a couple of datatypes and `scriptProperty` function 
```hs
scriptProperty :: String -> Generator p -> (TestData p -> ContextBuilder p) -> WithScript p ()
```
Which `'ForSpending` variant can (with some simplification) actually be represented as:
```hs
scriptProperty :: 
  ( ToData datum
  , ToData redeemer
  , FromData datum
  , FromData redeemer
  , Show datum
  , Show redeemer) => 
  String ->
  (datum -> redeemer -> Value -> Example) -> 
  Methodology datum -> 
  Methodology redeemer -> 
  Methodology Value -> 
  (datum -> redeemer -> Value -> ContextBuilder  'ForSpending)
  -> WithScript 'ForSpending ()
```
Here three separated generators disallows to:
- generate _coherent, bounded_ datum, redeemer, Value
Also, concrete function signatures and lack of free generator disallows to:
- use some generated data to control exactly `ContextBuilder` without touching datum, redeemer and Value
- use some generated data to control exactly case result prediction, without touching datum, redeemer and Value

Seems that such possibilities can be achieved by using one generator and more general functions for building test case from generated data.
So, the proposal is to change it into something like:
```hs
withProperty ::
  ( ToData datum
  , ToData redeemer
  , FromData datum
  , FromData redeemer
  , Show datum
  , Show redeemer
  ) =>
  String -> -- property name
  -- generated data can be any complex, so it's possible to keep there some metadata 
  -- to use in case result prediction and context building
  Methodology a -> -- data generator
  -- all stuff including prediction about case result is just a function from generated data
  (a -> (datum, redeemer, Value, ContextBuilder  'ForSpending, Maybe Example)) ->
  WithScript  'ForSpending ()
```
# Details
That was the way of representing things as one single function.
Now in terms of actual API. The only things this proposal offers to change is `Generator` and `scriptProperty`.
Instead of generating validator inputs separately we just require one generator and a way to extract them out of generated data.
That allows us generate _coherent_ arbitrarty validator inputs, and provide any additional data for usage in case building and result prediction.
```hs
data Generator (a :: Type) (p :: Purpose) where
  GenForSpending ::
    -- Gen can be any 'a'
    Methodology a ->
    -- But we must know how to make TestData and ContextBuilder from it
    (a -> (TestData 'ForSpending, ContextBuilder 'ForSpending)) ->
    Generator a 'ForSpending
  GenForMinting ::
    Methodology a ->
    (a -> (TestData 'ForMinting, ContextBuilder 'ForMinting)) ->
    Generator a 'ForMinting
```
The property itself (`a -> Maybe Example`) takes `a` as an argument, not `TestData p` or any more concrete type.
So it is more general and allows to build more restricted test builders based on this one.
That's important, so even if user can't find some concrete test builders satisfy his needs, will have possibility to make it by himself.
```hs
scriptProperty ::
  forall (a :: Type) (p :: Purpose).
  String -> -- property name
  Generator a p -> -- data generator
  (a -> Maybe Example) -> -- must it fail or succeed, or thrown away
  WithScript p ()
```
# Usage example
```hs
-- positive test
scriptProperty
  "From any pkh, CS, inital data and value its always possible to make valid context and transaction"
  (GenForSpending
    (Methodology (QC.arbitrary,QC.arbitrary,QC.arbitrary,QC.arbitrary) genericShrink)
    (\pkh cs initalData val -> 
        ( SpendingTest 
            MyDatum {owner = pkh, tokenCS = cs}
            (MyRedeemer $ mkMyRedeemer pkh initalData)
            (mkValidValue val cs)
        , buildValidContext pkh cs ))
  )
(const $ Just Good)
```

**Comment by Anteproperispomenon** [comment]
Maybe add a function that's just "any value produced by this generator should validate"? Because, if I'm not mistaken, the `scriptProperty` test will fail if there aren't roughly an equal number of failing and passing cases.

**Comment by sergesku** [comment]
## 5.0

### Added

* `passIf` combinator for creating `Outcome` from a condition.
* `TestItems (p :: Purpose)` type represens the data set for script checking
* `scriptPropertyFail` to test the conditions under which a script should always succeed
* `scriptPropertyPass` to test the conditions under which a script should always fail
* Property based testing example (test/Properties/Main.hs)

### Changed

* Rename `Example` to `Outcome` and its two constructors `Good` and `Bad` to
  `Pass` and `Fail` respectively, unifying with the internal type used in unit
  tests.
* Changed API for property based testing:
  * Changed type and implementation for `scriptProperty`
* `Generator (p :: Purpose)` replaced with `Generator (a :: Type) (p :: Purpose)`,
    changed types for data constructors `GenForSpending` and `GenForMinting`
* Property based testing coverage check changed from 0.5% to 45%

**Comment by AriFordsham** [comment]
Love it!
