### ISSUE TITLE
`^+` operator for `powNat` is confusing

### ISSUE THREAD

**Issue by adamczykm** [Liqwid-Labs/plutus-extra#91]
I've found `^+` operator that represents power function for naturals to be confusing, especially that the operator `^-` exists and is used to represent the `monus` function.
I'd vote to either remove the operator version of `powNat` - the name is intuitive and not that long, or to rename it to `^**` for example.

**Comment by kozross** [comment]
For @re-xyr: this is a major version bump to `plutus-numeric`, as it changes the API. I would be OK with either removing the operator version outright or renaming, but prefer removal. I'll let you make that call.
